name: NuGet Package
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2

    - name: showDir
      run: tree
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
 
    - name: Restore dependencies
      run: dotnet restore
 
    - name: Build
      run: dotnet build --configuration Release --no-restore
 
    - name: Test
      run: dotnet test --no-restore --verbosity normal
 
    - name: Pack
      run: dotnet pack --configuration Release --output dist --no-build --no-restore
